### ISSUE TITLE
small issue with partials and swig

### ISSUE THREAD

**Issue by jeromecoupe** [superwolff/metalsmith-layouts#38]
Hi there. Using the metalsmith CLI, I have trouble configuring / using partials with the Swig templating engine. Must be doing something stupid. Here is a reduced test case.

*metalsmith.json*
```
"metalsmith-layouts": {
      "engine": "swig",
      "directory": "layouts",
      "partials": "includes"
    }
```

*layouts/default.html*
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>This is a Metalsmith test</title>
  </head>
  <body>

    {% include "test.html" %}

    {{ contents|raw }}

  </body>
</html>
````

*src/index.html*
```
---
layout: default.html
---
<p>Hello world</p>
```

*includes/test.html*
```
<p>This is a test</p>
```

I get the following error

Metalsmith · ENOENT, no such file or directory '/data/weblocal/metalsmith_sandbox/layouts/pouet.html'

Any idea / pointer ?

**Comment by ismay** [comment]
Try this:

1. I'd move all layouts outside of `./src`. Otherwise you might end up with some unwanted recursiveness. Move them to `./layouts` for example (and remove the `directory` option).
2. Remove the partials option. It isn't necessary for swig includes.
3. Put your `test.html` include in `./layouts`. Swig includes are relative to the `layouts` directory, so that way `{% include "test.html" %}` should work.

Now it should work. Let me know.

**Comment by jeromecoupe** [comment]
Many thanks for coming back to me so quickly. Much appreciated.

1. Everything out of `./src` (typos in my original issue). I have left the directory option since I like to be explicit (team members are not familiar with Metalsmith)
2. and 3. Done. It does work like that. That was the issue I was having. Whatever I did before, it was always the `./layouts` folder that was called for includes

Couple of related questions

1. So Swig includes are always relative to the layouts directory ? Is there no way to have layouts and includes in separate directories w/ Swig ? I realise this is just cosmetic but I am used to Twig where this is definitely possible.

2. With metalsmith, is it possible to use the usual `{% block %}{% endblock %}` and `{% extends 'templates/default.html' %}` tags instead of Yaml front matter and `{{ content }}` tag ? If so, how do you do that ? I haven't managed to get it working.

Again, thanks for your help.

**Comment by ismay** [comment]
> So Swig includes are always relative to the layouts directory?

I'd have to test it to be sure (because each templating engine differs), but it's either relative to the `layouts` dir, or the current layout. Not certain which of those two it is (it ultimately depends on consolidate's implementation).

> Is there no way to have layouts and includes in separate directories w/ Swig?

You could, but then it would be something like `{% include "../includes/test.html" %}` instead of `{% include "test.html" %}` because of the relative path.

> With metalsmith, is it possible to use the usual {% block %}{% endblock %} and {% extends 'templates/default.html' %} tags instead of Yaml front matter and {{ content }} tag ?

Definitely. You can use both. Basically all that the yaml front matter does is define local variables. And the `contents` variable is just that, a variable. That variable is passed to the selected layout and the result is compiled.

But that being said; if you're going to use swig I'd recommend [metalsmith-in-place](https://github.com/superwolff/metalsmith-in-place). Metalsmith-layouts is just meant as a shim for languages that don't support template inheritance, like handlebars.

Check out https://github.com/ismay/ismaywolff.nl for an example. I'm using nunjucks, which is very similar to swig, so you should be able to adapt it to your liking. Let me know if that helps.

**Comment by ismay** [comment]
Oh, by the way, metalsmith-in-place render things a little differently, so when using extends and includes paths are relative to the root of the project (since there are no layouts). You'll see that in my repo.

**Comment by jeromecoupe** [comment]
ok. Will have a look. Still not very clear to me how to use that with the CLI but I guess I can figure it out with the various links you provided. Thanks again ! Coming from Jekyll here and the Metalsmith doc is rather sparse ;o)

**Comment by ismay** [comment]
> Coming from Jekyll here and the Metalsmith doc is rather sparse ;o) 

Yeah I know :). It can be frustrating but it's worth the effort I think. I'll update the readme to address your questions. 

Also, the boilerplates use the javascript api, but the basic configuration should work for the cli just as well. And if you're going to use extends don't forget to use metalsmith-filenames.

I'll close this, but feel free to let me know if you have any further questions!
