### ISSUE TITLE
Windows Missing helper: "strftime"

### ISSUE THREAD

**Issue by bnb** [superwolff/metalsmith-layouts#56]
Am trying to use metalsmith-layouts with Handlebars, and I am getting this error:

![2015-11-12_16-03-44](https://cloud.githubusercontent.com/assets/502396/11132064/d5882ef2-895b-11e5-88e0-9a04f761ed39.png)

Was getting a different error at first, which was all red and much longer. I solved that by `npm install handlebars --save` and including handlebars in my index file. Any idea as to what's wrong? Also tried installing strftime and including it, but that didn't do anything (as I imagined).

**Comment by ismay** [comment]
It can't find the `strftime` helper. If you've already tried attaching it to handlebars and it doesn't work, then I'd say that your `strftime` helper isn't a valid handlebars helper. If you can point me to a repository with a [reduced test case](https://css-tricks.com/reduced-test-cases/) I can take a look.

**Comment by bnb** [comment]
Reduced test case: https://github.com/bnb/bnb-metalsmith-layouts

**Comment by ismay** [comment]
Thanks. Ok so you're using a tag that implies the existence of a strftime helper here: https://github.com/bnb/bnb-metalsmith-layouts/blob/master/layouts/blog-post.hbs#L14. Which is why it tries to load a strftime helper.

And since you've not defined such a helper in build.js it throws an error. This is not a metalsmith-layouts issue so I'll close this, but look into handlebars helpers to solve this: http://blog.teamtreehouse.com/handlebars-js-part-2-partials-and-helpers

**Comment by bnb** [comment]
Thanks a ton!

**Comment by ismay** [comment]
:+1: No problem, hope it helps!
