### ISSUE TITLE
How to do partials with other engines

### ISSUE THREAD

**Issue by msaspence** [superwolff/metalsmith-layouts#73]
Specifically HAML

how does one render a partial?

**Comment by ismay** [comment]
Since this is more of a support question, would you mind opening your question on stack overflow? Feel free to use the [metalsmith tag](https://stackoverflow.com/questions/tagged/metalsmith), I'd be more than happy to help you there.

Closing now, but feel free to link to your question on SO, or reopen if this is a bug report.

**Comment by msaspence** [comment]
My thinking for putting on here was that one established it might be suitable to put in a pr for the readme

**Comment by ismay** [comment]
I understand. Problem is that there are a lot of supported engines, and putting engine specific instructions in the readme would make the readme way too large. Which is why I recommend SO, as I'm monitoring the metalsmith tag there and can help you there just as easily.

Also that way other people will be able to weigh in and your question can be easily found through google.
